config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get "/bien_vivre" => "pages#bien"
  get "/rendre_la_ville" => "pages#ville"
  get "/deplacer" => "pages#deplacer"
  get "/data" => "pages#data"
  get "/data1" => "pages#data1"
  get "/data2" => "pages#data2"
  get "/data3" => "pages#data3"
  get "/data4" => "pages#data4"
  get "/data5" => "pages#data5"
  get "/data6" => "pages#data6"
  get "/data7" => "pages#data7"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def home
  end

  def bien
  end

  def ville
  end

  def deplacer
  end

  def data
  end

  def data1
  end

  def data2
  end

  def data3
  end

  def data4
  end

  def data5
  end

  def data6
  end

  def data7
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Wise city</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
        <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>

    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css">

    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>


    <div id="footer">
      <div class="container">
        <div class="row">
          <div class="col-xs-6 col-sm-3">
            <ul class="list-inline social">
              <li>
                <a href="https://twitter.com/iceme">
                  <i class="fa fa-twitter"></i>
                </a>
              </li>
              <li>
                <a href="https://facebook.com/iceme">
                  <i class="fa fa-facebook"></i>
                </a>
              </li>
              <li>
                <a href="https://instagram.com/iceme">
                  <i class="fa fa-instagram"></i>
                </a>
              </li>
              <li>
                <a href="https://youtube.com/iceme">
                  <i class="fa fa-youtube"></i>
                </a>
              </li>
            </ul>
          </div>
          <div class="col-xs-6 col-sm-9">
            <p class="text-right">
              WISE CITY BOARD est une application fictive crée par
              <a href="http://www.weave.eu">weave</a>.
            </p>
          </div>
        </div>
      </div>
    </div>


    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
     <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/bien.html.erb
<div class="banner bien">
  <div class="banner-content">
    <h1>BIEN VIVRE</h1>
    <h2>Quelques infos </h2>
  </div>
</div>

      <%= link_to data_path do %>
        <div class="product">
          <div class='product-upvote'>
            <div class="product-arrow"></div>
            <div class='product-count'>1</div>
          </div>
          <%= image_tag("def.jpg", :class => "product-image hidden-xs") %>
          <div class='product-body'>
            <h3>68</h3>
            <p>Défribrillateurs disponibles dans les rues</p>
          </div>
        </div>
        <% end %>

        <%= link_to data1_path do %>
        <div class="product">
          <div class='product-upvote'>
            <div class="product-arrow"></div>
            <div class='product-count'>2</div>
          </div>
          <%= image_tag("bornewifi.jpg", :class => "product-image hidden-xs") %>
          <div class='product-body'>
            <h3>22</h3>
            <p>Bornes de WIFI public</p>
          </div>
        </div>
        <% end %>

        <%= link_to data2_path do %>
        <div class="product">
          <div class='product-upvote'>
            <div class="product-arrow"></div>
            <div class='product-count'>3</div>
          </div>
          <%= image_tag("zea.jpg", :class => "product-image hidden-xs") %>
          <div class='product-body'>
            <h3>41</h3>
            <p>Zones d'activitée économique</p>
          </div>
        </div>
        <% end %>

app/views/pages/data.html.erb
<div class="img-data">

</div>

  <div class="span6">
    <div class="flex-video widescreen"><iframe src="https://data.grandpoitiers.fr/explore/embed/dataset/environnement-defibrillateurs-grand-poitiers-donnees-metiers/map/?location=10,46.4905,0.56992&basemap=jawg.streets&static=false&datasetcard=true" width="1000" height="1000" frameborder="0"></iframe></div>
  <div class="span6">

<%= link_to "Retour !", bien_vivre_path %>

app/views/pages/data1.html.erb
<div class="img-data">

</div>

  <div class="span6">
    <div class="flex-video widescreen"><iframe src="https://data.grandpoitiers.fr/explore/embed/dataset/reseaux-point-de-couverture-wifi-grand-poitiers-donnees-metiers/map/?location=12,46.53726,0.27225&basemap=jawg.streets&static=false&datasetcard=true" width="400" height="300" frameborder="0"></iframe></iframe></div>
  <div class="span6">

<%= link_to "Retour !", bien_vivre_path %>

app/views/pages/data2.html.erb
<div class="img-data">

</div>

  <div class="span6">
    <div class="flex-video widescreen"><iframe src="https://data.grandpoitiers.fr/explore/embed/dataset/economie-zae-grand-poitiers-donnees-metiers/map/?dataChart=eyJxdWVyaWVzIjpbeyJjaGFydHMiOlt7InR5cGUiOiJjb2x1bW4iLCJmdW5jIjoiQVZHIiwieUF4aXMiOiJvYmplY3RpZCIsInNjaWVudGlmaWNEaXNwbGF5Ijp0cnVlLCJjb2xvciI6InJhbmdlLWN1c3RvbSJ9XSwieEF4aXMiOiJjY29jb20iLCJtYXhwb2ludHMiOjUwLCJzb3J0IjoiIiwic2VyaWVzQnJlYWtkb3duIjoibm9temFlIiwiY29uZmlnIjp7ImRhdGFzZXQiOiJlY29ub21pZS16YWUtZ3JhbmQtcG9pdGllcnMtZG9ubmVlcy1tZXRpZXJzIiwib3B0aW9ucyI6e319fV0sInRpbWVzY2FsZSI6IiJ9&location=12,46.58376,0.36598&basemap=jawg.streets&static=false&datasetcard=true" width="400" height="300" frameborder="0"></iframe></div>
  <div class="span6">

<%= link_to "Retour !", bien_vivre_path %>

app/views/pages/data3.html.erb
<div class="img-data">

</div>

  <div class="span6">
    <div class="flex-video widescreen"><iframe src="https://data.grandpoitiers.fr/explore/embed/dataset/environnement-balades-nature-grand-poitiers-donnees-metiers/map/?location=11,46.58888,0.3218&basemap=jawg.streets&static=false&datasetcard=true" width="400" height="300" frameborder="0"></iframe></div>
  <div class="span6">

<%= link_to "Retour !", rendre_la_ville_path %>

app/views/pages/data4.html.erb
<div class="img-data">

</div>

  <div class="span6">
    <div class="flex-video widescreen"><iframe src="https://data.grandpoitiers.fr/explore/embed/dataset/mobilite-bus-equipes-dune-motorisation-moins-polluante/analyze/?dataChart=eyJxdWVyaWVzIjpbeyJjaGFydHMiOlt7InR5cGUiOiJjb2x1bW4iLCJmdW5jIjoiU1VNIiwieUF4aXMiOiJub21icmUiLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiJyYW5nZS1BY2NlbnQifV0sInhBeGlzIjoiZW1wdHkiLCJtYXhwb2ludHMiOjUwLCJzb3J0IjoiIiwic2VyaWVzQnJlYWtkb3duIjoiYW5uZWUiLCJjb25maWciOnsiZGF0YXNldCI6Im1vYmlsaXRlLWJ1cy1lcXVpcGVzLWR1bmUtbW90b3Jpc2F0aW9uLW1vaW5zLXBvbGx1YW50ZSIsIm9wdGlvbnMiOnt9fX1dLCJ0aW1lc2NhbGUiOiIifQ%3D%3D&static=false&datasetcard=true" width="400" height="300" frameborder="0"></iframe></div>
  <div class="span6">


<%= link_to "Retour !", rendre_la_ville_path %>

app/views/pages/data5.html.erb
<div class="img-data">

</div>

  <div class="span6">
    <div class="flex-video widescreen"><iframe src="https://data.grandpoitiers.fr/explore/embed/dataset/mobilite-amenagements-cyclables-grand-poitiers-donnees-metiers/map/?location=11,46.59278,0.31497&basemap=jawg.streets&static=false&datasetcard=true" width="400" height="300" frameborder="0"></iframe></div>
  <div class="span6">


<%= link_to "Retour !", rendre_la_ville_path %>

app/views/pages/data6.html.erb
<div class="img-data">

</div>

  <div class="span6">
    <div class="flex-video widescreen"><iframe src="https://data.grandpoitiers.fr/explore/embed/dataset/espace-public-places-handicapees-gig-gic-grand-poitiers-donnees-metiers/map/?location=12,46.58166,0.35019&basemap=jawg.streets&static=false&datasetcard=true" width="400" height="300" frameborder="0"></iframe></div>
  <div class="span6">

<%= link_to "Retour !", deplacer_path %>

app/views/pages/data7.html.erb
<div class="img-data">

</div>

  <div class="span6">
    <div class="flex-video widescreen"><iframe src="https://data.grandpoitiers.fr/explore/embed/dataset/espace-public-arretes-de-travaux-voirie-grand-poitiers-donnees-metiers/map/?disjunctive.consequences_des_travaux&disjunctive.annee&disjunctive.nature_des_travaux_sce_communication&location=11,46.59251,0.31396&basemap=jawg.streets&static=false&datasetcard=true" width="400" height="300" frameborder="0"></iframe></div>
  <div class="span6">

<%= link_to "Retour !", deplacer_path %>

app/views/pages/deplacer.html.erb
<div class="banner deplacer">
  <div class="banner-content">
    <h1>SE DEPLACER</h1>
    <h2>Quelques infos </h2>
  </div>
</div>

  <%= link_to data6_path do %>
  <div class="product">
    <div class='product-upvote'>
      <div class="product-arrow"></div>
      <div class='product-count'>1</div>
    </div>
    <%= image_tag("place-handicapee.jpg", :class => "product-image hidden-xs") %>
    <div class='product-body'>
      <h3>95</h3>
      <p>Places réservés pour les personnes à mobilité réduite</p>
    </div>
  </div>
  <% end %>

<%= link_to data7_path do %>
  <div class="product">
    <div class='product-upvote'>
      <div class="product-arrow"></div>
      <div class='product-count'>2</div>
    </div>
    <%= image_tag("travaux.jpg", :class => "product-image hidden-xs") %>
    <div class='product-body'>
      <h3>1099</h3>
      <p>Travaux de voirie achevés en 2017</p>
    </div>
  </div>
  <% end %>
<!--
<%= link_to data5_path do %>
  <div class="product">
    <div class='product-upvote'>
      <div class="product-arrow"></div>
      <div class='product-count'>3</div>
    </div>
    <%= image_tag("travaux.jpg", :class => "product-image hidden-xs") %>
    <div class='product-body'>
      <h3>1099</h3>
      <p>Travaux de voirie achevés en 2017</p>
    </div>
  </div>
  <% end %> -->

app/views/pages/home.html.erb
<div class="wrapper">
      <div class="lead">
        <h1>GRAND POITIERS</h1>
        <h2>COMMUNAUTE URBAINE</h2>
        <p>
          <%= link_to 'Devenir notre partenaire', 'Grand Poitiers_Stratégie Smart City_Réponse technique-Weave_VersionFinale_pdf.pdf', class: "btn btn-primary btn-lg" %>
        </p>
      </div>
    </div>

    <div class="vertical-spacer"></div>

    <div class="container">
      <div class="row text-center">
        <h3>Consulter les données collaboratives du Grand Poitiers </h3>
      </div>

      <div class="row ">
        <div class="col-sm-12 col-md-4 feature">
          <%= link_to bien_vivre_path do %>
            <div class="item bien">
            <p>
              <strong>BIEN VIVRE</strong> <br>
            </p>
          </div>
        <% end %>
      </div>

        <div class="col-sm-12 col-md-4 feature">
          <%= link_to rendre_la_ville_path do %>
            <div class="item ville">
              <p>
                <strong>RENDRE LA VILLE PLUS VERTE</strong> <br>

              </p>
            </div>
        <% end %>
        </div>
          <div class="col-sm-12 col-md-4 feature">
          <%= link_to deplacer_path do %>
            <div class="item deplacer">
            <p>
              <strong>SE DEPLACER</strong> <br>

            </p>
          </div>
        <% end %>
        </div>

      </div>
    </div>

    <div class="vertical-spacer"></div>

app/views/pages/ville.html.erb
<div class="banner ville">
  <div class="banner-content">
    <h1>RENDRE LA VILLE PLUS VERTE</h1>
    <h2>Quelques infos </h2>
  </div>
</div>



  <%= link_to data3_path do %>
  <div class="product">
    <div class='product-upvote'>
      <div class="product-arrow"></div>
      <div class='product-count'>1</div>
    </div>
    <%= image_tag("balades.jpg", :class => "product-image hidden-xs") %>
    <div class='product-body'>
      <h3>20</h3>
      <p>Circuits de balade identifiés</p>
    </div>
  </div>
  <% end %>

<%= link_to data4_path do %>
  <div class="product">
    <div class='product-upvote'>
      <div class="product-arrow"></div>
      <div class='product-count'>2</div>
    </div>
    <%= image_tag("travaux.jpg", :class => "product-image hidden-xs") %>
    <div class='product-body'>
      <h3>123</h3>
      <p>Bus équipés de motorisation moins polluante</p>
    </div>
  </div>
  <% end %>

  <%= link_to data5_path do %>
  <div class="product">
    <div class='product-upvote'>
      <div class="product-arrow"></div>
      <div class='product-count'>3</div>
    </div>
    <%= image_tag("cyclable.jpg", :class => "product-image hidden-xs") %>
    <div class='product-body'>
      <h3>80</h3>
      <p>Aménagment cyclable</p>
    </div>
  </div>
  <% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top navbar-transparent" role="navigation">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Menu</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">
            WISE CITY
          </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <!-- <ul class="nav navbar-nav">
            <li class="active"><a href="#">Link</a></li>
            <li><a href="#">Link</a></li>
          </ul> -->
          <ul class="nav navbar-nav navbar-right">
            <li>
              <%= link_to "Accueil !", root_path %>
            </li>
            <li>
              <a href="https://weave.eu/" >Suivez-nous ! </a>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>